let prise=100;
/// "typeof varName" is used to find datatype of variable"///
console.log(prise);
console.log(typeof prise);
name="prathamesh";
console.log(name);
console.log(typeof name);
isFollow=true;
console.log(isFollow);
console.log(typeof isFollow);
let a;
console.log(a);
console.log(typeof a);
let x=null;
console.log(x);
console.log(typeof x);
let y=BigInt("12345");
console.log(y);
console.log(typeof y);
let z=Symbol("hellow");
console.log(z);
console.log(typeof z);